---

services:
  wp_php:
    container_name: wp_php
    image: app-php
    build: 
      context: .
      dockerfile: backend.dockerfile
    volumes:
      - ./wp-conf/simple-wp-config.php:/var/www/html/wp-config.php
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - wp_mysql
    networks:
      - app-network

  wp_mysql:
    container_name: wp_mysql
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_USER: default
      MARIADB_PASSWORD: default
      MARIADB_DATABASE: wordpress
      MARIADB_ROOT_PASSWORD: default
    volumes:
      - ./mariadb:/var/lib/mysql:Z
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge
