version: '3'
services:
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./etc/nginx/conf.d/site.conf:/etc/nginx/conf.d/default.conf
  #     - ./var/log/nginx/error.log:/var/log/nginx/error.log
  #     - ./var/log/nginx/access.log:/var/log/nginx/access.log
  #   ports:
  #     - 8080:80
  #   networks:
  #     - bridge
  php:
    build: 
      context: .
      dockerfile: backend.dockerfile
    container_name: php
    volumes:
      - ./app:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - bridge
  mysql:
    container_name: mysql
    image: clickhouse/clickhouse-server:23.1.2.9-alpine
    environment:
      - CLICKHOUSE_USER:default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT:1
      - CLICKHOUSE_PASSWORD:default
    volumes:
      - ./clickhouse-persistence:/bitnami/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
      - "9005:9005"
      - "9009:9009"
    networks:
      - bridge
    
networks:
  bridge:
    driver: bridge
